Fix createTursoClient() error handling
Propagate the error back to the callers so that we print out the actual
error to the user when not logged in, for example.

Before:

2023/03/28 13:19:22 error creating Turso client: user not logged in, please use turso auth login

After:

Error: user not logged in, please use turso auth login