Fix access token validation
Commit c2b284118f7579f2a07f60d260b4383069ad083a caused a regression in
the CLI because JWT validation in getAccessToken() is broken.

Before:

```
$ turso db create
Error: could not create database comic-humbug: Authentication required
```

After:

```
$ turso db create
Error: user not logged in, please login with turso auth login
```